# pubspec.yaml
name: simdokpol_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at https://developer.com/documentation/foundation/numbers_and_measurement/managing_your_app_s_version_and_build_numbers
# In Windows, build-name is used as productVersion while build-number used as productBuildFileVersion.
# Read more about Windows build-versioning at
# https://learn.microsoft.com/en-us/windows/msix/package/reserve-package-name#version-number-format
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Pastikan versi SDK Anda sesuai, ini contoh yang umum

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # === DATABASE ===
  sqflite: ^2.3.0+2          # Plugin SQLite utama untuk Flutter
  path: ^1.8.3               # Untuk menangani path file di berbagai OS
  sqflite_common_ffi: ^2.3.0+1 # Dukungan FFI untuk sqflite di platform desktop
  # sqflite_common_ffi_web: ^0.X.X # (Opsional) Jika nanti ingin dukungan web eksperimental

  # === STATE MANAGEMENT ===
  provider: ^6.0.5           # Pilihan state management yang populer dan mudah digunakan
  # bloc: ^8.1.2             # Alternatif state management yang lebih kompleks tapi kuat
  # flutter_bloc: ^8.1.3     # Integrasi BLoC dengan Flutter

  # === ROUTING ===
  go_router: ^12.1.1         # Pustaka routing deklaratif yang populer

  # === DESKTOP INTEGRATION ===
  system_tray: ^2.0.3        # Untuk ikon system tray dan menu konteks
  flutter_local_notifications: ^16.1.0 # Untuk notifikasi native di desktop/mobile

  # === PDF GENERATION AND PRINTING ===
  pdf: ^3.10.4               # Untuk membuat dokumen PDF secara programatis
  printing: ^5.11.1          # Untuk pratinjau cetak dan mencetak PDF

  # === UI/UTILITY PACKAGES ===
  intl: ^0.18.1              # Untuk format tanggal, angka, dll.
  # chart_sparkline: ^1.0.12 # Contoh untuk grafik sederhana di dashboard, ada banyak pilihan lain
  fl_chart: ^0.65.0          # Pustaka grafik yang lebih kaya fitur
  shared_preferences: ^2.2.2 # Untuk menyimpan preferensi pengguna sederhana

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See https://pub.dev/packages/flutter_lints for details.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # - assets/fonts/ # uncomment jika Anda punya font kustom
  # === SECURITY ===
  crypto: ^3.0.3             # Untuk hashing password (SHA256)

  # === UTILITY ===
  shared_preferences: ^2.2.2 # Untuk menyimpan preferensi pengguna sederhana (mis. ID user login)


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

